version: "3.4"

services:
  postgresql:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=metal_grimoire_dev
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: team@golo.io
      PGADMIN_DEFAULT_PASSWORD: test123
    ports:
      - "8888:80"
